- name: Install php extensions
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - php7.0
    - php7.0-mysql
    - php7.0-common
    - php7.0-cli
    - php7.0-intl
    - php7.0-curl
    - php7.0-cgi
    - php7.0-fpm
    - php7.0-gd
    - php7.0-mcrypt
    - php7.0-mbstring
    - libapache2-mod-php7.0

  notify:
    - restart apache2
